### ISSUE TITLE
Group event posts by year

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#74] opened 2021-11-08 23:11 UTC
The mockup has the posts grouped by year, with the year showing up in the left column. 

That wasn't implemented in #65, since it's tricky to do without [dynamic templates](https://github.com/WordPress/gutenberg/issues/32939), and not essential for the launch.

This is interrelated with #75

**Comment by ryelle** [comment] 2022-02-15 16:36
This is a duplicate of #281, which has the mockup screenshot & some discussion. Closing in favor of that issue.

**Closed as completed by ryelle** 2022-02-15 16:36 UTC
Labels: [Type] Enhancement
