### ISSUE TITLE
SotW test and visual polish People of WordPress footer block

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-news-2021#102] opened 2021-12-02 05:13 UTC
The People of WordPress footer block on the news homepage needs testing and improvements for the SotW demo. Here's a recent screenshot from the [test site](https://wordpress.org/news-test/):
<img width="1464" alt="Screen Shot 2021-12-02 at 4 14 57 pm" src="https://user-images.githubusercontent.com/7200686/144361967-f222b303-06a6-4f72-88e6-55def8c00f8f.png">

There are some visual differences from the [figma design](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4659%3A8683). We need someone to:

- [ ] Test the People of WP footer block
- [ ] Open issues in the SotW milestone for anything that must be fixed in time for the demo
- [ ] Discuss here, propose solutions, and open PRs if possible

**Comment by ryelle** [comment] 2021-12-02 22:02
I was playing with this in Inspector, and adding `width: 100% !important` to [the `.wp-block-post-featured-image` here](https://github.com/WordPress/wporg-news-2021/blob/f407f50fc715ef950ce3fa26012505d8b55357fc/source/wp-content/themes/wporg-news-2021/sass/components/front-page/_people-of-wordpress.scss#L40) gives an interesting effect (the `important` is needed to override an inline width).

<img width="1319" alt="Screen Shot 2021-12-02 at 5 00 11 PM" src="https://user-images.githubusercontent.com/541093/144510166-0fbce708-5878-4ccf-b409-726a58138464.png">

<img width="898" alt="Screen Shot 2021-12-02 at 5 00 50 PM" src="https://user-images.githubusercontent.com/541093/144510171-e9af23e0-17ab-4285-84dd-50cfcfff049c.png">

![Screen Shot 2021-12-02 at 17 01 00](https://user-images.githubusercontent.com/541093/144510202-5346e62a-d259-4ff6-adcd-3d5ee90cbb40.png)

I'd make a PR but I don't have a working dev env at the moment 😅

**Comment by scruffian** [comment] 2021-12-07 16:30
This looks like a duplicate of https://github.com/WordPress/wporg-news-2021/issues/96

**Closed as completed** 2021-12-08 07:39 UTC
Labels: Good First Issue, Help Wanted
