### ISSUE TITLE
Front page: See all… links don't work

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-news-2021#115] opened 2021-12-08 22:15 UTC
The "See all…" links on the front page don't work as expected. They all stay on the front page, loading the next page of the main query, which is just the Latest Posts section. Each link circled should go to a different page

![Screen Shot 2021-12-08 at 17 08 57](https://user-images.githubusercontent.com/541093/145292603-227d57ed-4914-4ac8-80df-a482b4274de8.png)

- "See all releases" should link to the releases category
- "See all posts" should link to an "All posts" page
- "See all people" should probably link to the People of WordPress tag, I don't see a mockup for this (but I'd guess it should be like the community category page)

**Comment by tellyworth** [comment] 2021-12-13 05:36
See #126 for a partial fix.

"See All Posts" isn't right, I'm trying to think of a good simple SotW hack to get a default post excerpt view with all posts shown.

**Comment by iandunn** [comment] 2021-12-13 17:10
This looks like a duplicate of #70, but please reopen if there's anything distinct that I missed

> "See all posts" should link to an "All posts" page

That's `/page/2`, background is in https://github.com/WordPress/wporg-news-2021/issues/55#issuecomment-953650339 and these code blocks:

https://github.com/WordPress/wporg-news-2021/blob/b63360fa17be22eb87a3654c68bde9147edfafe3/source/wp-content/themes/wporg-news-2021/functions.php#L136-L171

https://github.com/WordPress/wporg-news-2021/blob/b63360fa17be22eb87a3654c68bde9147edfafe3/source/wp-content/themes/wporg-news-2021/functions.php#L190-L214

**Closed as completed by iandunn** 2021-12-13 17:10 UTC

**Comment by ryelle** [comment] 2021-12-13 17:37
That issue doesn't capture these. I'll leave it up to you whether to add these to that issue, reopen this, or create a new issue

- "See all releases" should link to the releases category
- "See all people" should probably link to the People of WordPress tag, I don't see a mockup for this (but I'd guess it should be like the community category page)

> That's `/page/2`

Yep, but it doesn't link to that page.

**Comment by iandunn** [comment] 2021-12-14 16:15
> "See all releases" should link to the releases category

I was thinking the current `wp:query-pagination-next` should do that, since it's inside a query block that for that category.  Is that not the case?

I know the link is currently broken, but that seems like a bug in our code or upstream, and #70 is for fixing that. I'd prefer to use the proper blocks and dynamic data, rather than hardcoding stuff. I don't mind doing that if we really have to, though.


> "See all people" should probably link to the People of WordPress tag

The posts are pulled from [the Interviews category](https://wordpress.org/news/category/interviews/), so I assumed it'd link there


>  it doesn't link to that page.

Yeah, #70 should fix that if I'm not mistaken

**Comment by ryelle** [comment] 2021-12-14 16:44
> I was thinking the current `wp:query-pagination-next` should do that, since it's inside a query block that for that category. Is that not the case?

I don't think so. I think the expectation is that the pagination link will show the next group of posts in this same block/page (and it doesn't work now because we don't set a unique `queryId`). If it should link off to the category, that's a separate page, and would need a hardcoded link.

> The posts are pulled from the Interviews category, so I assumed it'd link there

They're currently being pulled from [the People of WordPress tag](https://github.com/WordPress/wporg-news-2021/blob/b63360fa17be22eb87a3654c68bde9147edfafe3/source/wp-content/themes/wporg-news-2021/block-template-parts/front-page/people-of-wordpress.html#L1), but whatever the real tag/category should be, the link doesn't go there.
