### ISSUE TITLE
Horizontal scrolling on home page

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#224] opened 2022-01-22 15:28 UTC
<img width="784" alt="Screen Shot 2022-01-22 at 7 24 09 AM" src="https://user-images.githubusercontent.com/484068/150644718-9a7259b9-1ef3-4334-b679-b1c271170a44.png">

seems to happen on all breakports in firefox. i haven't checked other pages or browsers. i started noticing it after the #207 PRs merged, so it may already be on @shaunandrews' radar, but i wanted to get in an issue for it in case it's not

**Comment by ryelle** [comment] 2022-01-22 16:22
Yeah I caught this on #207 too — it's caused by the background images overflowing the container, behind the latest release & behind "See all people".

**Comment by shaunandrews** [comment] 2022-01-24 18:07
Fixed in #236

**Closed as completed** 2022-01-24 18:06 UTC
Labels: [Type] Bug
