### ISSUE TITLE
Seeing horizontal scroll bars from .front__site-title::after

### ISSUE THREAD

**Issue by 0aveRyan** [WordPress/wporg-news-2021#261] opened 2022-01-28 21:40 UTC
Seeing horizontal scroll bars, likely need an `overflow-x: hidden` at some level.

![Screenshot 2022-01-28 at 14 37 02](https://user-images.githubusercontent.com/9565066/151625131-301accf4-ca6b-4984-84d5-ba0951e090c3.jpg)

Appears to be originating from `.front__site-title::after`

**Comment by ryelle** [comment] 2022-01-28 21:47
Duplicate of #253.

**Closed as completed by ryelle** 2022-01-28 21:47 UTC
