### ISSUE TITLE
Discrepancy between news header and the rest of w.org

### ISSUE THREAD

**Issue by zackkrida** [WordPress/wporg-news-2021#332] opened 2022-02-17 14:57 UTC
Apologies if this has been reported elsewhere, but there's a slight layout shift between the News header and the header on the rest of w.org. The easiest way to notice this is that on the default screen size of a 13" macbook pro, Openverse is cut off on news but not elsewhere. This seems to be caused by the value of the CSS variable `--wp--preset--font-size--small`, which is `13px` on w.org but `14px` on News.

> News

![CleanShot 2022-02-17 at 09 54 59@2x](https://user-images.githubusercontent.com/6351754/154507520-36c20a03-c521-4b6c-aa48-d161d99f51d2.png)

> Rest of w.org

![CleanShot 2022-02-17 at 09 54 49@2x](https://user-images.githubusercontent.com/6351754/154507720-874c670f-fbfe-4cb6-86ec-f8973a4ef71b.png)

**Comment by ryelle** [comment] 2022-02-17 15:08
Could be related to https://github.com/WordPress/wporg-mu-plugins/issues/86#issuecomment-1027265151, though that showed the opposite problem — 13px (correct) on News, and 14px elsewhere.

**Comment by ryelle** [comment] 2022-02-17 16:25
Correction to my previous comment — the font size _should_ be 14px now, it was updated in https://github.com/WordPress/wporg-mu-plugins/commit/f44d0ba06785c2b2c2081d6d9b45306bcefce461.

**Comment by ryelle** [comment] 2022-02-17 18:58
Actually, my reading comprehension was off (it was pre-☕ ) — this _is_ a duplicate of https://github.com/WordPress/wporg-mu-plugins/issues/86. I'm going to close this issue, since the fix will happen in `wporg-mu-plugins`.

**Closed as completed by ryelle** 2022-02-17 18:58 UTC
