### ISSUE TITLE
Misalignments and visual problems on posts and content

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-news-2021#356] opened 2022-02-28 18:13 UTC
I opened up some posts randomly and found out that there's something wrong with alignments. Perhaps that's due to some on-going tasks but I thought I'd flag these out anyway because these have been addressed before and were looking good.

- [x]  In Podcast the content width is too small

<img width="1533" alt="Captura de ecrã 2022-02-28, às 17 37 48" src="https://user-images.githubusercontent.com/65220155/156032149-f1d7354a-ba7f-474e-8c44-5996ce6ff926.png">

- [x]  In the posts the post meta isn't aligned with "News" in the Local Nav Bar. @iandunn maybe this is happening due to the changes in [this PR](https://github.com/WordPress/wporg-news-2021/pull/352). I think if that's the case, it's better to adopt [the initial idea](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=11920%3A47029) of keeping the elements that are either left or right aligned to the edges always that way.

<img width="1533" alt="Captura de ecrã 2022-02-28, às 17 44 55" src="https://user-images.githubusercontent.com/65220155/156032252-7b988586-90f1-401f-9cda-7030454224d0.png">

- [x]  The images that are set to full-width in the editor don't look full width. They should be full-width across all sizes.

<img width="1533" alt="Captura de ecrã 2022-02-28, às 17 46 03" src="https://user-images.githubusercontent.com/65220155/156032399-dbe4f7a7-d973-4be0-a1ae-e9149d38813e.png">

- [ ]  In Events and Releases the spacings between the post titles and post date are non existent — let's revert this to what it was before.

https://user-images.githubusercontent.com/65220155/156033714-058f97ca-b5d5-4041-a11e-8deb84a27ab9.mp4

- [ ]  In both Events and Releases, the post excerpts font size is looking way too big for a 1536px screen size. These sizes should only become bigger in really large screens, from 2000px on.

- [ ]  Let's try to use [this alignment](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=11980%3A53269) only from 2000px on, I thought that was how it was going to behave and I'm not happy with how it looks now, it seems to start getting those side margins at 1040px. For before 2000px let's use [this alignment](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4852%3A36290).

- [ ]  At 1536px the pre footer's font size is also too big. Let's apply the rules above to that section too.

<img width="1536" alt="Captura de ecrã 2022-02-28, às 18 14 22" src="https://user-images.githubusercontent.com/65220155/156036076-689cdb2b-15f8-4ad8-831c-6ba6698c1621.png">

**Comment by iandunn** [comment] 2022-02-28 21:10
> In Events and Releases the spacings between the post titles and post date are non existent

Do you mean between the `2021` date, or the `December 16, 2021` date? I see the expected spacing for the latter.

For the former, I think that only appears when you resize quickly, it's caused by the CSS animation. If you stop at that width for a half second it should snap to the normal spacing.

**Comment by iandunn** [comment] 2022-02-28 21:21
> In both Events and Releases, the post excerpts font size is looking way too big for a 1536px screen size. These sizes should only become bigger in really large screens, from 2000px on.

This is what it'd look like at `1432px` wide:

<img width="1430" alt="Screen Shot 2022-02-28 at 1 18 14 PM" src="https://user-images.githubusercontent.com/484068/156060223-6ceaa44b-3921-4ba5-84c5-42211b5df9d4.png">

That's `114` characters long, while the optimal seems to be around `66`. 

At `1900px` wide, it'd be `143` characters long.

**Comment by iandunn** [comment] 2022-02-28 21:31
> Let's try to use [this alignment](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=11980%3A53269) only from 2000px on,

If we do remove the extra padding on the left/right edges, it makes the above issue even worse, and Releases would have `172` characters at `1900px` wide.

Although, #352 did add a `max-width` on the content, since that seemed like it existed in the mockup of smaller screens, but it was never added to the code. If we keep that but remove everything else, it'd fix the text issue, but would look like this at `1900px`:

<img width="1895" alt="Screen Shot 2022-02-28 at 1 30 34 PM" src="https://user-images.githubusercontent.com/484068/156061875-7db047f5-71b5-4934-886f-acb2818ebb81.png">

**Comment by iandunn** [comment] 2022-02-28 21:38
> At 1536px the pre footer's font size is also too big

Do you mean the "bottom banner" (Follow the Code, Find an Event, etc)? That has similar issues as above, but less pronounced. It'd result in `90` characters at `1870px` wide, and `100` characters at `1999px`.

**Comment by iandunn** [comment] 2022-02-28 22:35
The first three items are fixed now.

**Comment by iandunn** [comment] 2022-02-28 23:24
Another idea for https://github.com/WordPress/wporg-news-2021/issues/356#issuecomment-1054683544 would be to follow what happens on individual posts. The content would have `max-width: var(--wp--custom--layout--content-size)` and `margin: auto`. With that, the left column stays where it is, but the content column is centered among the remaining space.

**Comment by beafialho** [comment] 2022-03-02 10:27
> Do you mean between the 2021 date, or the December 16, 2021 date? I see the expected spacing for the latter.

The post's December 16, 2021 date. There's no spacing below the post title, see the difference:

| Currently | With Spacing |
| --- | ----------- |
| <img width="1536" alt="Captura de ecrã 2022-03-02, às 10 03 47" src="https://user-images.githubusercontent.com/65220155/156340876-7a03d297-2ed8-4526-8557-37e7d143cff1.png">  |  <img width="1536" alt="Captura de ecrã 2022-03-02, às 10 06 31" src="https://user-images.githubusercontent.com/65220155/156340911-b55a87fe-6fe2-4f7c-9789-e55bf7ee684c.png">  |
| <img width="1536" alt="Captura de ecrã 2022-03-02, às 10 08 58" src="https://user-images.githubusercontent.com/65220155/156341363-365a1255-5352-4b61-a3c8-69638f0ea5b7.png">  |  <img width="1536" alt="Captura de ecrã 2022-03-02, às 10 09 22" src="https://user-images.githubusercontent.com/65220155/156341381-121dc8d3-e5e0-40e1-8653-9330b17d5012.png"> |

> This is what it'd look like at 1432px wide:

That shouldn't happen because the column of that text should be smaller:

<img width="1028" alt="Captura de ecrã 2022-03-02, às 10 01 10" src="https://user-images.githubusercontent.com/65220155/156339732-eca9f886-c13b-4d71-9710-76d9f62cf078.png">

> Another idea for https://github.com/WordPress/wporg-news-2021/issues/356#issuecomment-1054683544 would be to follow what happens on individual posts. The content would have max-width: var(--wp--custom--layout--content-size) and margin: auto. With that, the left column stays where it is, but the content column is centered among the remaining space.

I think this might be the closest to what we're trying to achieve which is generally, unless we're in really large screens, we shouldn't increase the font size to meet the optimal character limit, we should define the content width to make sure it doesn't pass that limit.

I'm having a hard time explaining the intentions for the design here and I need to spend some time thinking about how this will scale up as a whole, including the bottom banner and maybe footer. I'll get back to you once I have clearer directions so that you don't have to redo things over and over.

**Comment by iandunn** [comment] 2022-03-02 17:04
> There's no spacing below the post title

Oh, I see, it only happens when a descender falls below the baseline. I'll look into that 👍🏻

**Comment by iandunn** [comment] 2022-03-02 19:23
I added the margin and line height that was missing. We may need to tweak it once we change the font-size, though, so I'll leave the corresponding checkbox empty for now.

**Comment by beafialho** [comment] 2022-03-03 10:52
Ok, after reflecting on this for a while, and taking a look at some other site examples ([here](https://www.newyorker.com) and [here](https://www.apple.com/newsroom/)) and how they usually handle this, I realized that we may be making this more complicated than it really is.

Currently if we open a News post at a large screen size, the font size stays the same, as well as the content width. If we want to see it bigger we can simply zoom in and everything will scale up together. 

https://user-images.githubusercontent.com/65220155/156545340-d3c966d2-966a-45f6-b02f-80802cbcf0ed.mp4

We pass character limit by a few characters but the posts are comfortable to read. I think this is where other elements such as line height, the heading sizes and the overall cleanness of the pages also help.

So I suggest we revert all the changes from [this PR](https://github.com/WordPress/wporg-news-2021/pull/352) and and have it be how it was before with the same font size across all desktop sizes (on mobile it's different like the mockups).

One thing we can do though is apply this responsive behaviour to the bottom banner from 1900px on, where we turn the 2 column layout into a 4 column one. That's a better way to adapt the content in large screens, while keeping the same font size:

<img width="1077" alt="Captura de ecrã 2022-03-03, às 10 18 22" src="https://user-images.githubusercontent.com/65220155/156545572-04c025a9-0084-4b21-a6ee-e0fa111fde9c.png">

I added mockups for the bottom banner [here](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=12216%3A69511), and also for [Community](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=12216%3A69197) and [Month in WP](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=12216%3A71385) which behave similarly to the banner when scaled up.

For other pages, we don't need to do anything (See [these](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=12217%3A75913)).

**Comment by iandunn** [comment] 2022-03-03 16:43
> taking a look at some other site examples ([here](https://www.newyorker.com/) and [here](https://www.apple.com/newsroom/)) and how they usually handle this

They have a `max-width` on the entire content area, so that's never wider than `1475px` and `980px`, respectively. Do you want to place anything like that here? It seems like growing infinitely is a big part of the problem. 

Even on an average 21" monitor, there're large gaps between the footer columns, a single post title and its post meta, etc.

The bg colors could still stretch to the edges if that's desirable.

> One thing we can do though is apply this responsive behaviour to the bottom banner from 1900px on, where we turn the 2 column layout into a 4 column one. 

That looks great 👍🏻 


> revert all the changes from https://github.com/WordPress/wporg-news-2021/pull/352 and have it be how it was before with the same font size across all desktop sizes

Do you want to revert the the extra margins too, or just the font sizes?

What do you want to do to fix original issue? Apply the `max-width` and centering behavior to releases/events, in the same way that individual posts have?

**Comment by beafialho** [comment] 2022-03-03 17:41
> Do you want to place anything like that here?

I think setting the paragraphs to be a fixed width as shown [here](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=11920%3A47029) works. Quotes and media should go full width just as they do now. Does that make sense?

<img width="504" alt="Captura de ecrã 2022-03-03, às 17 23 20" src="https://user-images.githubusercontent.com/65220155/156618104-1ea2a4d8-8559-49cc-b62a-07504dac82a6.png">

> Do you want to revert the the extra margins too, or just the font sizes?

Extra margins too.

> What do you want to do to fix original issue? Apply the max-width and centering behavior to releases/events, in the same way that individual posts have?

I thought reverting font sizes and extra margins fixed the issue? 

The main idea is to make sure the elements on the left are always aligned with the global and local headers elements and that the post lists width are fixed. I've mocked them all up [here](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=12217%3A75913) because I couldn't explain it very well with words 😅 Take a look and let me know if that makes sense.

<img width="1468" alt="Captura de ecrã 2022-03-03, às 17 16 07" src="https://user-images.githubusercontent.com/65220155/156616528-dc3f84a1-4d74-4c24-b943-705d5ee4d278.png">

<img width="838" alt="Captura de ecrã 2022-03-03, às 17 39 39" src="https://user-images.githubusercontent.com/65220155/156620818-ac1cc91e-8ee4-4821-981d-6ce3a67b01e1.png">

<img width="849" alt="Captura de ecrã 2022-03-03, às 17 39 46" src="https://user-images.githubusercontent.com/65220155/156620847-2dfb0aa2-67e0-408b-9041-1981f25678f3.png">

<img width="861" alt="Captura de ecrã 2022-03-03, às 17 40 03" src="https://user-images.githubusercontent.com/65220155/156620871-e05de0c0-63d1-42f9-a0da-d8844e091f1a.png">

**Comment by iandunn** [comment] 2022-03-03 18:42
> I thought reverting font sizes and extra margins fixed the issue?

Not exactly, but I think I know what you mean. I'll revert the extra margins and font-size, but keep some of the other parts that brought it closer to the mockup. Then we can take a look at a screen capture to be sure.

**Comment by vijayhardaha** [comment] 2022-03-17 04:33
Issue on page [WordPress.org News](https://wordpress.org/news/)

Latest Release section is not optimized for width between `>780px` & `<1280px`
--

iPad Pro (Portrait) - Not OK
![Dev Tools Screenshot](https://i.snipboard.io/M4vKSR.jpg)

iPad Air (Landscape) - Not OK
![iPad Device screenshot](https://i.snipboard.io/wK13pV.jpg)

iPad Air (Portrait) - Not OK
![iPad Device screenshot](https://i.snipboard.io/WvHSTc.jpg)

___

Overflow problem on width `<=375px`
---

There is overflowX on `>=375px` because class `.front__latest-posts-heading` used for section heading has calculated width but doesn't not `max-width` defined to handle the `overflow`

![Overflow on Dev Tools](https://i.snipboard.io/5jvriR.jpg)
![Overflow on Screen Resize](https://i.snipboard.io/4OpXxn.jpg)

Font too big for width between `>=375px` & `<=480px`
---

We could use a bit smaller font size to avoid `text-overflow`
> Needs testing on small width iPhone(s) to see the actual output.

![Font too big](https://i.snipboard.io/aFsxXJ.jpg)

**Comment by iandunn** [comment] 2022-03-17 16:30
The homepage font size / overflow aren't related to this issue, so I created #364 for it.

**Closed as completed** 2022-03-21 20:14 UTC
Labels: [Type] Bug
