### ISSUE TITLE
Fix broken pagination links

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#70] opened 2021-11-05 20:21 UTC
It looks like all the uses of pagination are broken.

- [ ]  `front-page/` template parts - "See all ..." links to `/?query-page=2` instead of `/page/2`. That might be a bug with `wp:query-pagination-next`, or maybe we're using it wrong. See #55
- [x] archive/category templates - links to pages have broken `query-page` param instead of `page/n` format
- [x] archive/category templates - shown even when cat only has 1 post
- [ ] Look for those problems in other templates too, and fix any instances

**Comment by jeffikus** [comment] 2021-12-07 19:00
@scruffian @matiasbenedetto is this related to any of the work we've been doing on pagination? Anything we can use from there to help here?

**Comment by scruffian** [comment] 2021-12-09 12:04
No, this is unrelated

**Comment by ryelle** [comment] 2021-12-14 16:52
It looks like if you use `inherit` on the main posts query, the pagination link on "See All Posts" should link to /page/2/ https://github.com/WordPress/gutenberg/issues/32531#issuecomment-877992554

```html
<!-- wp:query {"query":{"perPage":5,"inherit":"true"},"tagName":"section","className":"front__latest-posts","align":"full"} -->
```

**Comment by tellyworth** [comment] 2021-12-17 06:02
> It looks like if you use `inherit` on the main posts query

The problem with this is that when you use `inherit` the query block seems to ignore other query parameters like `perPage`. I'm not sure if that's expected behaviour or a bug.

**Comment by ryelle** [comment] 2021-12-17 15:12
That's a good question. It looks like [the block query gets merged into the main query](https://github.com/WordPress/gutenberg/blob/9d4474c1c4c486947d479ecb817c4303ba8dfa86/packages/block-library/src/post-template/index.php#L29), but values in the main query will override the block values… I think that is intended. If you try this through the editor, hitting "Inherit query from template" turns off all the UI controls for taxonomies and per-page settings.

**Comment by tellyworth** [comment] 2021-12-22 06:42
Thanks for digging that up @ryelle.  I'm pretty sure the code in `render_block_core_post_template()` has a number of undesirable side effects that are going to cause problems for block themes. As well as the `perPage` thing noted above, this means you get inconsistent versions of query vars in filters. I think I'll have to write up some detailed test cases to clarify and figure out how to move forward.

**Closed as completed** 2022-01-18 19:33 UTC
Labels: [Type] Bug, [Team] Neso
